services:
  web:
    container_name: web
    image: php:8.2-cli
    ports:
      - 80:80
    volumes:
      - ./src:/web
      - ./deploy/.env:/web/app/.env
    command: bash -c "docker-php-ext-install pdo_mysql; php -t /web/app/public -S 0.0.0.0:80"
    networks:
      - bytemarket-network
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb:11.4.2
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - ./deploy/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - bytemarket-network

networks:
  bytemarket-network:
    driver: bridge