services:
  web:
    container_name: web
    image: php:8.2-cli
    ports:
      - 80:80
    volumes:
      - ../src:/web
      - ./.env:/web/app/.env
    command: bash -c "docker-php-ext-install pdo_mysql; php -t /web/app/public -S 0.0.0.0:80"
    networks:
      web-db:
        ipv4_address: 172.16.0.100
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb:11.4.2
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      web-db:
        ipv4_address: 172.16.0.101

networks:
  web-db:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1