@startuml
title Inicio de Sesión del Cliente / Administrador
start

repeat :Introduce el correo y la contraseña en los campos;
    :Pulsa al botón de Iniciar Sesión;
    backward:Mensajes de error programado en los campos;
repeat while (¿Datos incorrectos?) is (Sí)

:Envía los datos a la API REST;
if (¿Existe el cliente en la base de datos?) then (Sí)
    :Comparar contraseña del cliente introducido;
    if (¿Contraseña coincide con la de la base de datos?) then (Sí)
        :Crear una Sesión;
        #greenyellow:Código de éxito HTTP 200 (OK);
        :Redirigir al cliente a la página principal;
    else (No)
        #salmon:Usuario o contraseña incorrecta;
    endif
else (No)
    #salmon:Usuario o contraseña incorrecta;
endif
stop
@enduml